/**
 * Generates public/sitemap.xml and public/robots.txt from the public URL inventory.
 * Run: npm run seo:generate
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildPublicUrlInventory,
  CANONICAL_SITE_URL,
  type PublicUrlEntry,
  type SitemapChangeFreq,
} from "../lib/seo/publicUrlInventory";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderUrlEntry(entry: PublicUrlEntry, lastmod: string): string {
  return `  <url>
    <loc>${escapeXml(entry.url)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${entry.changefreq as SitemapChangeFreq}</changefreq>
    <priority>${entry.priority.toFixed(2)}</priority>
  </url>`;
}

function renderSitemap(entries: PublicUrlEntry[], lastmod: string): string {
  const urls = entries.map((e) => renderUrlEntry(e, lastmod)).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function renderRobots(): string {
  return `# Generated by scripts/generate-seo.ts - do not edit by hand.
User-agent: *
Allow: /

Disallow: /api/
Disallow: /admin/
Disallow: /private/
Disallow: /thank-you

Sitemap: ${CANONICAL_SITE_URL}/sitemap.xml
`;
}

function main(): void {
  const inventory = buildPublicUrlInventory();
  const lastmod = todayUtc();

  mkdirSync(PUBLIC_DIR, { recursive: true });

  const sitemapPath = join(PUBLIC_DIR, "sitemap.xml");
  const robotsPath = join(PUBLIC_DIR, "robots.txt");

  writeFileSync(sitemapPath, renderSitemap(inventory.entries, lastmod), "utf8");
  writeFileSync(robotsPath, renderRobots(), "utf8");

  console.log(`Wrote ${inventory.entries.length} URLs to public/sitemap.xml`);
  console.log(`Wrote public/robots.txt (Sitemap: ${CANONICAL_SITE_URL}/sitemap.xml)`);

  if (inventory.entries.length < 30) {
    console.warn(
      "Warning: URL count is lower than expected. Ensure case-types and guides data are available."
    );
  }
}

main();
